/**
 * Generated by bondlink.routing.JavaScriptReverseRouter
 *
 * To add routes to this file, you must first add them to the action associated
 * with the URL: /issuer-portal/typescript-routes.
 *
 * To generate routes: curl --insecure -o /src/bondlink/web/issuerportal/assets/scripts/portalRouter.ts https://dev.bondlink.org/issuer-portal/typescript-routes
 *
 */

import {Router} from "./router";

export class PortalRouter extends Router {

  static readonly issuerportal = {
    "AccountsController": {
      "addExistingUser":  function(userId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/accounts/existing/" + encodeURIComponent((function(k:string,v:string) {return v})("userId", userId0))}) },
      "create":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/accounts"}) },
      "dataTable":  function() { if (true) { return Router._wA({method: "GET", url: "/" + "issuer-portal/accounts/data-table"}) } },
      "delete":  function(userId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/accounts/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("userId", userId0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/accounts"}) },
      "updateRole":  function(userId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/accounts/update-role/" + encodeURIComponent((function(k:string,v:string) {return v})("userId", userId0))}) }
      },
    "AnalystsController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/analysts/data-table"}) },
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/analysts/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/analysts/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/analysts"}) }
      },
    "AnalyticsController": {
      "daAction":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/analytics/document-statistics"}) },
      "daDataTable":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/analytics/document-statistics/data-table"}) },
      "documentActivity":  function(docId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/analytics/document-statistics-detail" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("docId", docId0)])}) },
      "oversightTraffic":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/compliance-monitoring/traffic-analysis"}) },
      "oversightTrafficDt":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/compliance-monitoring/traffic-analysis/data-table"}) },
      "trafficAnalysis":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/analytics/traffic-analysis"}) },
      "trafficAnalysisDt":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/analytics/traffic-analysis/data-table"}) }
      },
    "BondOfferingsController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/offerings/data-table"}) },
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/offerings/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/offerings/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/offerings"}) }
      },
    "Cusip6Controller": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/cusip6/data-table"}) },
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/cusip6/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/cusip6/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/cusip6"}) }
      },
    "DocumentTypesController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/document-categories/data-table"}) },
      "delete":  function(rowId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/document-categories/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("rowId", rowId0)])}) },
      "edit":  function(rowId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/document-categories/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("rowId", rowId0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/document-categories"}) },
      "post":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/document-categories"}) }
      },
    "DocumentsDisclaimerController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/document-disclaimer"}) }
      },
    "DraftsController": {
      "approval":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/draft/approval"}) }
      },
    "EmmaController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/emma/data-table"}) },
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/emma/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/emma/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/emma"}) }
      },
    "FeaturedImagesController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/featured-images/data-table"}) },
      "edit":  function(mediaId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/featured-images/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("mediaId", mediaId0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/featured-images"}) }
      },
    "FinancialCalendarController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/calendar/dataTable"}) },
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/calendar/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/calendar/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/calendar"}) }
      },
    "GlobalCalloutsController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/global-callouts/data-table"}) },
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/global-callouts/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/global-callouts/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "hide":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/global-callouts/hide/" + encodeURIComponent((function(k:string,v:string) {return v})("id", id0))}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/global-callouts"}) },
      "show":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/global-callouts/show/" + encodeURIComponent((function(k:string,v:string) {return v})("id", id0))}) }
      },
    "InternalLinksController": {
      "allItems":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/internal-links/items"}) }
      },
    "InvestorActivityController": {
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/investor-activity/delete/" + encodeURIComponent((function(k:string,v:string) {return v})("id", id0))}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/investor-activity/edit/" + encodeURIComponent((function(k:string,v:string) {return v})("id", id0))}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/investor-activity"}) },
      "investorDetails":  function(u0:string,c1:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/investor-activity/details" + Router._qS([(function(k:string,v:string){return v!=null?(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})(k,v): ''})("u", u0), (function(k:string,v:string){return v!=null?(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})(k,v): ''})("c", c1)])}) },
      "preview":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/investor-activity/preview"}) }
      },
    "IssuerAboutController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/about"}) }
      },
    "IssuerCalloutsController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/callout/data-table"}) },
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/callout/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/callout/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/callout"}) }
      },
    "IssuerController": {
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/settings/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/settings"}) },
      "setPrimaryOfficer":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/officers/primary"}) }
      },
    "IssuerDisclaimerController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/general-disclaimer"}) }
      },
    "IssuerFaqController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/faq/data-table"}) },
      "delete":  function(faqId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/faq/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("faqId", faqId0)])}) },
      "edit":  function(faqId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/faq/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("faqId", faqId0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/faq"}) }
      },
    "IssuerFinanceController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/finance-team"}) }
      },
    "IssuerNewsController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/news/data-table"}) },
      "delete":  function(newsId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/news/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("newsId", newsId0)])}) },
      "edit":  function(newsId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/news/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("newsId", newsId0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/news"}) },
      "togglePostType":  function(newsId0:string,postTypeId1:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/news/toggle" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("newsId", newsId0), (function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("postTypeId", postTypeId1)])}) }
      },
    "IssuerOfficersController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/officers/data-table"}) },
      "delete":  function(issuerOfficerId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/officers/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("issuerOfficerId", issuerOfficerId0)])}) },
      "edit":  function(issuerOfficerId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/officers/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("issuerOfficerId", issuerOfficerId0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/officers"}) },
      "photo":  function(issuerOfficerId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/officers/photo" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("issuerOfficerId", issuerOfficerId0)])}) }
      },
    "IssuerPagesController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/pages"}) },
      "upsertTitle":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/pages/title"}) }
      },
    "IssuerProjectsController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/infrastructure-projects/data-table"}) },
      "delete":  function(projectId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/infrastructure-projects/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("projectId", projectId0)])}) },
      "edit":  function(projectId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/infrastructure-projects/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("projectId", projectId0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/infrastructure-projects"}) }
      },
    "IssuerSiteTemplateController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/site-template"}) }
      },
    "IssuerSplashController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/splash"}) }
      },
    "IssuerWelcomeController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/welcome"}) }
      },
    "LogoController": {
      "delete":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/logo/delete"}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/logo"}) }
      },
    "MenuItemsController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/menu-items/data-table"}) },
      "delete":  function(hrefId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/menu-items/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("hrefId", hrefId0)])}) },
      "edit":  function(hrefId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/menu-items/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("hrefId", hrefId0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/menu-items"}) }
      },
    "MonitoringController": {
      "stats":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/compliance-monitoring"}) }
      },
    "NotificationSettingsController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/notification-settings"}) },
      "investorSubscriptions":  function(typeId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/investor-notifications/subscriptions" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("typeId", typeId0)])}) }
      },
    "NotificationSubscriptionsPortalController": {
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "portal/notification-subscriptions/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "deleteIssuer":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "portal/notification-subscriptions/delete-issuer" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "portal/notification-subscriptions"}) },
      "notifications":  function() { return Router._wA({method: "GET", url: "/" + "portal/issuer-notifications"}) },
      "userIssuerSub":  function(issuerId0:string,newSub1:string) { return Router._wA({method: "GET", url: "/" + "portal/notification-subscriptions/issuer" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("issuerId", issuerId0), (function(k:string,v:string){return k+'='+(!!v)})("newSub", newSub1)])}) }
      },
    "OfferingDisclaimerController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/offering-disclaimer"}) }
      },
    "OfferingInformationController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/offering-info"}) }
      },
    "OfferingParticipantsController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/offering-participants/data-table"}) },
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/offering-participants/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/offering-participants/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/offering-participants"}) }
      },
    "OversightDocRulesController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/compliance-monitoring/settings/dataTable"}) },
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/compliance-monitoring/settings/delete/" + encodeURIComponent((function(k:string,v:string) {return v})("id", id0))}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/compliance-monitoring/settings/" + encodeURIComponent((function(k:string,v:string) {return v})("id", id0))}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/compliance-monitoring/settings"}) }
      },
    "PaymentsController": {
      "invoices":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/invoices"}) },
      "issuerUserAgreement":  function(freq0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/issuer-user-agreement" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("freq", freq0)])}) },
      "payments":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/payments"}) }
      },
    "RatingsController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/ratings/data-table"}) },
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/ratings/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/ratings/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/ratings"}) }
      },
    "RegistrationController": {
      "basics":  function() { return Router._wA({method: "GET", url: "/" + "issuer-registration/basics"}) }
      },
    "RelatedIssuersController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/related/data-table"}) },
      "delete":  function(rowId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/related/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("rowId", rowId0)])}) },
      "edit":  function(rowId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/related/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("rowId", rowId0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/related"}) }
      },
    "RoadShowsController": {
      "dataTable":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/road-shows/data-table"}) },
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/road-shows/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "edit":  function(id0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/road-shows/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/road-shows"}) },
      "post":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/road-shows/post"}) }
      },
    "SearchDocumentsController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/search-documents"}) }
      },
    "SiteSetupController": {
      "index":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/site-setup"}) }
      },
    "SortController": {
      "sort":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/sort"}) }
      },
    "UploadController": {
      "archive":  function(mediaId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/upload/archive/" + encodeURIComponent((function(k:string,v:string) {return v})("mediaId", mediaId0))}) },
      "dataTable":  function() { if (true) { return Router._wA({method: "GET", url: "/" + "issuer-portal/upload/data-table"}) } },
      "delete":  function(mediaId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/upload/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("mediaId", mediaId0)])}) },
      "documents":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/upload/documents"}) },
      "edit":  function(mediaId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/upload/edit" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("mediaId", mediaId0)])}) },
      "emmaReceiptsCsv":  function(mediaId0:string) { return Router._wA({method: "GET", url: "/" + "issuer-portal/upload/emma-receipts/csv" + Router._qS([(function(k:string,v:string){return v!=null?(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})(k,v): ''})("mediaId", mediaId0)])}) },
      "oversight":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/upload/oversight/documents"}) },
      "post":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/upload/post"}) },
      "postPrivate":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/upload/private/post"}) },
      "privateDocuments":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/upload/private/documents"}) },
      "unarchive":  function(mediaId0:string) { return Router._wA({method: "POST", url: "/" + "issuer-portal/upload/unarchive/" + encodeURIComponent((function(k:string,v:string) {return v})("mediaId", mediaId0))}) },
      "uploadHelper":  function() { return Router._wA({method: "GET", url: "/" + "issuer-portal/upload/helper"}) },
      "validatePost":  function() { return Router._wA({method: "POST", url: "/" + "issuer-portal/upload/validate-post"}) }
      },
    "UserPortalController": {
      "delete":  function(id0:string) { return Router._wA({method: "POST", url: "/" + "portal/saved-documents/delete" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("id", id0)])}) },
      "savedDocuments":  function() { return Router._wA({method: "GET", url: "/" + "portal/saved-documents"}) },
      "settings":  function() { return Router._wA({method: "GET", url: "/" + "portal/settings"}) },
      "updatePushAlertToken":  function() { return Router._wA({method: "POST", url: "/" + "portal/update-pushalert-token"}) }
      }
    };
}
