/**
 * Generated by bondlink.routing.JavaScriptReverseRouter
 *
 * To add routes to this file, you must first add them to the action associated
 * with the URL: /issuer-sites/typescript-routes.
 *
 * To generate routes: curl --insecure -o /src/bondlink/web/issuersites/assets/scripts/sitesRouter.ts https://dev.bondlink.org/issuer-sites/typescript-routes
 *
 */

import {Router} from "./router";

export class SitesRouter extends Router {

  static readonly common = {
    "EmailController": {
      "unsubscribe":  function(email0:string,issuerId1:string) { return Router._wA({method: "GET", url: "/" + "emails/unsubscribe" + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("email", email0), (function(k:string,v:string){return v!=null?(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})(k,v): ''})("issuerId", issuerId1)])}) }
      }
    };

  static readonly issuersites = {
    "BondOfferingsController": {
      "offering":  function(issuerId0:string,issuerSlug1:string,offeringId2:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/bond-offering/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0) + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("offeringId", offeringId2)])}) },
      "offerings":  function(issuerId0:string,issuerSlug1:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/bond-offerings/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) }
      },
    "CalendarController": {
      "index":  function(issuerId0:string,issuerSlug1:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/financial-calendar/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) }
      },
    "EmmaController": {
      "ajaxTable":  function(issuerId0:string,issuerSlug1:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/emma-filings/ajax/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) },
      "index":  function(issuerId0:string,issuerSlug1:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/emma-filings/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) }
      },
    "InvestorsController": {
      "login":  function() { if (true) { return Router._wA({method: "GET", url: "/" + "investors/login"}) } },
      "signIn":  function() { return Router._wA({method: "POST", url: "/" + "investors/login"}) },
      "signUp":  function() { return Router._wA({method: "POST", url: "/" + "investors/register"}) }
      },
    "IssuerController": {
      "contact":  function(issuerId0:string,issuerSlug1:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/contact/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) },
      "index":  function(issuerId0:string,issuerSlug1:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) },
      "news":  function(issuerId0:string,issuerSlug1:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/news/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) },
      "team":  function(issuerId0:string,issuerSlug1:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/team/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) }
      },
    "NotificationSubscriptionsController": {
      "subscribeToIssuer":  function(issuerId0:string) { return Router._wA({method: "POST", url: "/" + "portal/notification-subscription/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) }
      },
    "RatingsController": {
      "index":  function(issuerId0:string,issuerSlug1:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/bond-ratings/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) }
      },
    "RelatedIssuersController": {
      "index":  function(issuerId0:string,issuerSlug1:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/related-issuers/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) }
      },
    "ReportsController": {
      "archiveDocuments":  function(issuerId0:string,issuerSlug1:string,mediaCategoryId2:string,docTypeId3:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/archive-documents/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0) + Router._qS([(function(k:string,v:string){return v!=null?(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})(k,v): ''})("mediaCategoryId", mediaCategoryId2), (function(k:string,v:string){return v!=null?(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})(k,v): ''})("docTypeId", docTypeId3)])}) },
      "downloadRedirectAjax":  function(issuerId0:string,issuerSlug1:string,mediaId2:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/download-report/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0) + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("mediaId", mediaId2)])}) },
      "filterArchive":  function(issuerId0:string,issuerSlug1:string,mediaCategoryId2:string,mediaYear3:string) { return Router._wA({method: "POST", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/filter-archive/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0) + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("mediaCategoryId", mediaCategoryId2), (function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("mediaYear", mediaYear3)])}) },
      "filterDocuments":  function(issuerId0:string,issuerSlug1:string,mediaCategoryId2:string,mediaYear3:string) { return Router._wA({method: "POST", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/filter-documents/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0) + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("mediaCategoryId", mediaCategoryId2), (function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("mediaYear", mediaYear3)])}) },
      "financialDocuments":  function(issuerId0:string,issuerSlug1:string,mediaCategoryId2:string,docTypeId3:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/financial-documents/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0) + Router._qS([(function(k:string,v:string){return v!=null?(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})(k,v): ''})("mediaCategoryId", mediaCategoryId2), (function(k:string,v:string){return v!=null?(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})(k,v): ''})("docTypeId", docTypeId3)])}) },
      "shareMedia":  function(issuerId0:string,issuerSlug1:string,mediaId2:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/share-media/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0) + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("mediaId", mediaId2)])}) }
      },
    "RoadShowController": {
      "reportProgress":  function() { return Router._wA({method: "POST", url: "/" + "roadshow/report"}) },
      "roadShow":  function(issuerId0:string,issuerSlug1:string,roadShowId2:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/roadshow/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0) + Router._qS([(function(k:string,v:string) {return encodeURIComponent(k)+'='+encodeURIComponent(v)})("roadShowId", roadShowId2)])}) },
      "roadShows":  function(issuerId0:string,issuerSlug1:string) { return Router._wA({method: "GET", url: "/" + encodeURIComponent((function(k:string,v:string) {return v})("issuerSlug", issuerSlug1)) + "/roadshows/i" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) }
      },
    "SavedDocumentsController": {
      "remove":  function() { return Router._wA({method: "POST", url: "/" + "portal/remove-saved-document"}) },
      "save":  function() { return Router._wA({method: "POST", url: "/" + "portal/saved-documents"}) }
      }
    };
}
