/**
 * Generated by bondlink.routing.JavaScriptReverseRouter
 *
 * To add routes to this file, you must first add them to the action associated
 * with the URL: /issuer-sites/widget-typescript-routes.
 *
 * If you have added a new controller, please add it to the type definitions at:
 * /src/bondlink/web/typings/browser/ambient/jsRoutes/jsRoutes.d.ts
 *
 * To generate routes: curl -o /src/bondlink/web/issuersites/assets/scripts/widgetsRouter.ts http://dev.bondlink.org:9000/issuer-sites/widget-typescript-routes
 *
 */

import {Router} from "./router";

export class WidgetsRouter extends Router {

  static readonly issuersites = {
    "WidgetsController": {
      "issuer":  function(issuerId0:string) { return Router._wA({method: "GET", url: "/" + "widget/issuer/wi" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) },
      "relatedIssuers":  function(issuerId0:string) { return Router._wA({method: "GET", url: "/" + "widget/related-issuers/wi" + (function(k:string,v:string) {return v})("issuerId", issuerId0)}) }
    }
  };
}
